---
- name: Detect Docker
  shell: /bin/grep -q "docker" /proc/1/cgroup
  register: docker_installed
  ignore_errors: True

- name: Docker Message
  debug: msg="This host is running inside a docker container"
  when: docker_installed.rc == 0

- name: Check that root location exists
  file: path={{ark_nodejs_install_loc}} state=directory recurse=yes

- name: Copy artifact from local location
  copy: src={{ark_nodejs_local_loc}}/{{ark_nodejs_archive_file}}
        dest={{ark_nodejs_install_loc}}
  when: ark_nodejs_install_mode == "local"

- name: Copy artifact from remote url
  get_url: url={{ark_nodejs_remote_fullurl}}
           dest={{ark_nodejs_install_loc}}
  when: ark_nodejs_install_mode == "remote"

- name: Ensure directory {{ark_nodejs_install_loc}}/{{ark_nodejs_app_name}} exists
  file: path={{ark_nodejs_install_loc}}/{{ark_nodejs_app_name}}
        state=directory

- name: Unzip artifact {{ark_nodejs_archive_file}} within {{ark_nodejs_install_loc}}
  command: unzip -o {{ark_nodejs_archive_file}} -d {{ark_nodejs_app_name}}
           chdir="{{ark_nodejs_install_loc}}"

- name: Link latest
  file: src={{ark_nodejs_exec}}
        dest={{ark_nodejs_symlink}}
        owner=root group=root
        state=link

- name: Link for docker
  file: src={{ark_nodejs_exec}}
        dest={{ark_nodejs_install_root}}/nodejs_app.js
        owner=root group=root
        state=link
  when: docker_installed.rc == 0

- name: NPM Install global packages
  npm: name={{item}} global=yes
  with_items: ark_nodejs_global_packages

- name: Get NPM dependencies for the app
  command: npm install --production
           chdir="{{ark_nodejs_install_loc}}/{{ark_nodejs_app_name}}"

- name: Create init.d script
  template: src=init.j2 dest="/etc/init.d/{{ark_nodejs_service_name}}"
    owner="root" group="root" mode=0755
  notify:
    - Restart nodejs app
